/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: ACMP (Analog Comparator)
*              Example for ModusToolbox.
*              Comparator block(ANACMP-1) is configured to receive divided 
*              Reference voltage on positive input (IN-P) pin. Users may then 
*              modify the voltage to negative input pin (IN-N) pin (Port 2.6) 
*              and watch the user LED toggle according to ANACMP1:CMP_OUT change.
* 
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"

#include "xmc_acmp.h"

/*******************************************************************************
* Defines
*******************************************************************************/
#define COMP_INST_1     1

/*****************************************************************************
 * GLOBAL DATA
 *****************************************************************************/
/* ACMP Slice configuration */
XMC_ACMP_CONFIG_t g_acmp_config =
{
  .filter_disable = 0U,                         /*Glitch filter is active*/
  .output_invert = 0U,                          /*No inversion of comparator output*/
  .hysteresis = XMC_ACMP_HYSTERESIS_20          /*20mV hysteresis to reduce noise sensitivity*/
};

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It sets up the comparator to receive Reference
* voltage on IN-P pin.Bit field CMP_OUT of ANACMP1 register changes its state
* based on the input applied on IN-N pad. The input to Comparator pin IN-N (Pin 2.6)
* can be modified to see ANACMP1:CMP_OUT register status to change. An LED is
* toggled depending upon the register status.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize comparator ACMP1 instance */
    XMC_ACMP_Init(XMC_ACMP0, COMP_INST_1, &g_acmp_config);

    /* Connect divided reference(VACMP_REF/2) to IN-P of ACMP1 */
    XMC_ACMP_EnableReferenceDivider();

    /* Enable comparator ACMP1 instance */
    XMC_ACMP_EnableComparator(XMC_ACMP0, COMP_INST_1);

    /* Users may now apply inputs on P2.6 and evaluate USER LED output */
    while(1U)
    {
        /* Toggle USER LED depending on comparator output */
        if((COMPARATOR->ANACMP1) & COMPARATOR_ANACMP1_CMP_OUT_Msk)
        {
            /* Output low turns LED ON when comparator output is high */
            XMC_GPIO_SetOutputLow(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
        }
        else
        {
            /* Output low turns LED OFF when comaparator output is low */
            XMC_GPIO_SetOutputHigh(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
        }
        /* Infinite loop */
    }

}

/* [] END OF FILE */
